[package]
name = "layered-io"
version = "0.2.2-alpha.0"
description = "I/O traits extending Read and Write"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["api", "io", "stream"]
categories = ["os", "rust-patterns"]
repository = "https://github.com/sunfishcode/layered-io"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.3"

[dependencies]
duplex = "0.1.0"
unsafe-io = { version = "0.5.0", features = ["os_pipe"] }
terminal-io = { version = "0.2.0", optional = true }
futures-io = { version = "0.3.12", optional = true }

[badges]
maintenance = { status = "actively-developed" }
